### ISSUE TITLE
hapi requires stream2 streams, rot13-stream is a stream stream

### ISSUE THREAD

**Issue by martinheidegger** [ccarruitero/makemehapi#100]
```
Debug: internal, implementation, error
    TypeError: Cannot read property 'objectMode' of undefined
    at internals.Response._streamify (/project/node_modules/hapi/lib/response.js:450:34)
    at internals.Response._marshal (/project/node_modules/hapi/lib/response.js:433:21)
    at /project/node_modules/hapi/lib/transmit.js:119:18
    at /project/node_modules/hapi/lib/transmit.js:529:20
    at Object.exports.parallel (/project/node_modules/hapi/node_modules/items/lib/index.js:47:9)
    at Object.internals.state (/project/node_modules/hapi/lib/transmit.js:498:11)
    at Object.internals.marshal (/project/node_modules/hapi/lib/transmit.js:96:15)
    at Object.exports.send (/project/node_modules/hapi/lib/transmit.js:27:15)
    at /project/node_modules/hapi/lib/request.js:367:18
    at /project/node_modules/hapi/node_modules/hoek/lib/index.js:781:22
```

this error occurs when you try to use an old stream with hapi8 (related to #99). rot13-stream is a very old implementation. https://github.com/ajcrites/rot13-transform works better.

**Comment by rhrn** [comment]
`stream.pipe(request.raw.res);`
